"""Init tables

Revision ID: 9e7e653d3fe8
Revises: 
Create Date: 2024-11-17 22:55:44.990507

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e7e653d3fe8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insurance_calculate_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "date",
            sa.DateTime(),
            nullable=False,
            comment="Дата расчета страховки",
        ),
        sa.Column(
            "cargo_type", sa.String(), nullable=False, comment="Тип груза"
        ),
        sa.Column(
            "declared_value",
            sa.Float(),
            nullable=False,
            comment="Объявленное значение груза",
        ),
        sa.Column(
            "insurance_cost",
            sa.Float(),
            nullable=False,
            comment="Стоимость страховки",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "date",
            sa.DateTime(),
            nullable=False,
            comment="Дата загрузки тарифов",
        ),
        sa.Column(
            "cargo_type", sa.String(), nullable=False, comment="Тип груза"
        ),
        sa.Column("rate", sa.Float(), nullable=False, comment="Тариф"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rates")
    op.drop_table("insurance_calculate_history")
    # ### end Alembic commands ###
